@ECHO OFF

CALL "%ProgramW6432%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

REM CURL_DIR and OPENSSL_DIR must contain include and lib directories. 
REM Runntime MT and MTd supported


SET CURL_DIR=
SET OPENSSL_DIR=C:\openssl\openssl64\
SET OPENSSL_CA_FILE=B:\ksi-c-api\test\resource\tlv\mock.crt

REM nmake clean
del out\lib\libksiapiMTd.lib
rem nmake RTL=MTd NET_PROVIDER=CURL CRYPTO_PROVIDER=CRYPTOAPI CURL_DIR="%CURL_DIR%" OPENSSL_CA_FILE="%OPENSSL_CA_FILE%" OPENSSL_DIR="%OPENSSL_DIR%" all
rem nmake RTL=MTd NET_PROVIDER=CURL TRUST_PROVIDER=OPENSSL HASH_PROVIDER=CRYPTOAPI CURL_DIR="%CURL_DIR%" OPENSSL_CA_FILE="%OPENSSL_CA_FILE%" OPENSSL_DIR="%OPENSSL_DIR%" test

nmake test RTL=MDd DLL=lib NET_PROVIDER=WINHTTP CRYPTO_PROVIDER=OPENSSL OPENSSL_CA_FILE="%OPENSSL_CA_FILE%" libMTd
pause
